export interface Theme {
    name: string;
    swatch: string;
    dark: boolean;
    vars: Record<string, string>;
}

export const THEMES: Theme[] = [
    // ── Light themes ──────────────────────────────────────────────────────────
    {
        name: 'Lavender',
        swatch: '#7F77DD',
        dark: false,
        vars: {
            '--accent':         '#7F77DD',
            '--accent-light':   '#EEEDFE',
            '--accent-dark':    '#3C3489',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#f5f5f3',
            '--bg-tertiary':    '#eeede9',
            '--text-primary':   '#1a1a1a',
            '--text-secondary': '#666660',
            '--text-tertiary':  '#a0a09a',
            '--border':         '#e4e4e0',
        },
    },
    {
        name: 'Ocean',
        swatch: '#0ea5e9',
        dark: false,
        vars: {
            '--accent':         '#0ea5e9',
            '--accent-light':   '#e0f2fe',
            '--accent-dark':    '#0369a1',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#f0f9ff',
            '--bg-tertiary':    '#e0f2fe',
            '--text-primary':   '#0c1a2e',
            '--text-secondary': '#4a6a8a',
            '--text-tertiary':  '#8ab0c0',
            '--border':         '#bae6fd',
        },
    },
    {
        name: 'Forest',
        swatch: '#16a34a',
        dark: false,
        vars: {
            '--accent':         '#16a34a',
            '--accent-light':   '#dcfce7',
            '--accent-dark':    '#14532d',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#f0fdf4',
            '--bg-tertiary':    '#dcfce7',
            '--text-primary':   '#0a1a0f',
            '--text-secondary': '#3a6a4a',
            '--text-tertiary':  '#7aa08a',
            '--border':         '#bbf7d0',
        },
    },
    {
        name: 'Sunset',
        swatch: '#ea580c',
        dark: false,
        vars: {
            '--accent':         '#ea580c',
            '--accent-light':   '#ffedd5',
            '--accent-dark':    '#7c2d12',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#fff7ed',
            '--bg-tertiary':    '#ffedd5',
            '--text-primary':   '#1a0a00',
            '--text-secondary': '#6a3a1a',
            '--text-tertiary':  '#a07050',
            '--border':         '#fed7aa',
        },
    },
    {
        name: 'Rose',
        swatch: '#e11d48',
        dark: false,
        vars: {
            '--accent':         '#e11d48',
            '--accent-light':   '#ffe4e6',
            '--accent-dark':    '#881337',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#fff1f2',
            '--bg-tertiary':    '#ffe4e6',
            '--text-primary':   '#1a0a0f',
            '--text-secondary': '#6a1a2a',
            '--text-tertiary':  '#a06070',
            '--border':         '#fecdd3',
        },
    },
    {
        name: 'Slate',
        swatch: '#475569',
        dark: false,
        vars: {
            '--accent':         '#475569',
            '--accent-light':   '#f1f5f9',
            '--accent-dark':    '#1e293b',
            '--bg-primary':     '#ffffff',
            '--bg-secondary':   '#f8fafc',
            '--bg-tertiary':    '#f1f5f9',
            '--text-primary':   '#0f172a',
            '--text-secondary': '#475569',
            '--text-tertiary':  '#94a3b8',
            '--border':         '#e2e8f0',
        },
    },
    {
        name: 'Amber',
        swatch: '#d97706',
        dark: false,
        vars: {
            '--accent':         '#d97706',
            '--accent-light':   '#fef3c7',
            '--accent-dark':    '#78350f',
            '--bg-primary':     '#fffbeb',
            '--bg-secondary':   '#fef9e7',
            '--bg-tertiary':    '#fef3c7',
            '--text-primary':   '#1c0f00',
            '--text-secondary': '#6a4a1a',
            '--text-tertiary':  '#a08050',
            '--border':         '#fde68a',
        },
    },
    {
        name: 'Grape',
        swatch: '#7c3aed',
        dark: false,
        vars: {
            '--accent':         '#7c3aed',
            '--accent-light':   '#ede9fe',
            '--accent-dark':    '#4c1d95',
            '--bg-primary':     '#fdfbff',
            '--bg-secondary':   '#f5f0fe',
            '--bg-tertiary':    '#ede9fe',
            '--text-primary':   '#1a0a2e',
            '--text-secondary': '#5a3a8a',
            '--text-tertiary':  '#9a7ac0',
            '--border':         '#ddd6fe',
        },
    },

    // ── Dark themes ───────────────────────────────────────────────────────────
    {
        name: 'Midnight',
        swatch: '#8B83F7',
        dark: true,
        vars: {
            '--accent':         '#8B83F7',
            '--accent-light':   '#1e1a3a',
            '--accent-dark':    '#b0aaf9',
            '--bg-primary':     '#141414',
            '--bg-secondary':   '#1f1f1f',
            '--bg-tertiary':    '#2a2a2a',
            '--text-primary':   '#f0f0f0',
            '--text-secondary': '#909090',
            '--text-tertiary':  '#606060',
            '--border':         '#333333',
        },
    },
    {
        name: 'Deep Ocean',
        swatch: '#38bdf8',
        dark: true,
        vars: {
            '--accent':         '#38bdf8',
            '--accent-light':   '#0c2a3a',
            '--accent-dark':    '#7dd3fc',
            '--bg-primary':     '#0f1923',
            '--bg-secondary':   '#162130',
            '--bg-tertiary':    '#1c2d40',
            '--text-primary':   '#e0f2fe',
            '--text-secondary': '#7a9ab5',
            '--text-tertiary':  '#4a6a85',
            '--border':         '#22374f',
        },
    },
    {
        name: 'Deep Forest',
        swatch: '#4ade80',
        dark: true,
        vars: {
            '--accent':         '#4ade80',
            '--accent-light':   '#0a2015',
            '--accent-dark':    '#86efac',
            '--bg-primary':     '#0d1a12',
            '--bg-secondary':   '#142018',
            '--bg-tertiary':    '#1a2c20',
            '--text-primary':   '#dcf5e7',
            '--text-secondary': '#6aa87a',
            '--text-tertiary':  '#3a6050',
            '--border':         '#1e3828',
        },
    },
    {
        name: 'Ember',
        swatch: '#fb923c',
        dark: true,
        vars: {
            '--accent':         '#fb923c',
            '--accent-light':   '#2a1800',
            '--accent-dark':    '#fdba74',
            '--bg-primary':     '#1a0f08',
            '--bg-secondary':   '#231610',
            '--bg-tertiary':    '#2e1e14',
            '--text-primary':   '#fdebd5',
            '--text-secondary': '#b87a55',
            '--text-tertiary':  '#805040',
            '--border':         '#3a2010',
        },
    },
    {
        name: 'Crimson',
        swatch: '#f43f5e',
        dark: true,
        vars: {
            '--accent':         '#f43f5e',
            '--accent-light':   '#2a0615',
            '--accent-dark':    '#fb7185',
            '--bg-primary':     '#1a0812',
            '--bg-secondary':   '#230f1a',
            '--bg-tertiary':    '#2e1522',
            '--text-primary':   '#fde4ea',
            '--text-secondary': '#b87090',
            '--text-tertiary':  '#804060',
            '--border':         '#3a1020',
        },
    },
    {
        name: 'Graphite',
        swatch: '#94a3b8',
        dark: true,
        vars: {
            '--accent':         '#94a3b8',
            '--accent-light':   '#1a2030',
            '--accent-dark':    '#cbd5e1',
            '--bg-primary':     '#111318',
            '--bg-secondary':   '#181c24',
            '--bg-tertiary':    '#1f242e',
            '--text-primary':   '#e2e8f0',
            '--text-secondary': '#8899aa',
            '--text-tertiary':  '#505f70',
            '--border':         '#2a3444',
        },
    },
    {
        name: 'Obsidian',
        swatch: '#a78bfa',
        dark: true,
        vars: {
            '--accent':         '#a78bfa',
            '--accent-light':   '#1a1230',
            '--accent-dark':    '#c4b5fd',
            '--bg-primary':     '#0c0c12',
            '--bg-secondary':   '#121218',
            '--bg-tertiary':    '#181820',
            '--text-primary':   '#f5f3ff',
            '--text-secondary': '#7870b0',
            '--text-tertiary':  '#484080',
            '--border':         '#222230',
        },
    },
    {
        name: 'Dark Amber',
        swatch: '#fbbf24',
        dark: true,
        vars: {
            '--accent':         '#fbbf24',
            '--accent-light':   '#251800',
            '--accent-dark':    '#fcd34d',
            '--bg-primary':     '#130e00',
            '--bg-secondary':   '#1c1500',
            '--bg-tertiary':    '#261c00',
            '--text-primary':   '#fef3c7',
            '--text-secondary': '#a08040',
            '--text-tertiary':  '#705830',
            '--border':         '#322200',
        },
    },
];

export function applyTheme(index: number): void {
    const theme = THEMES[index] ?? THEMES[0];
    const root = document.documentElement;
    for (const [key, val] of Object.entries(theme.vars)) {
        root.style.setProperty(key, val);
    }
}
